### PR TITLE
Command processor fix

### LINKED ISSUE #675: Fails to install via dalamud luncher
**Which plugin are you referring to?**
AetheryteLinkInChat

Fails to load after initial installation via dalamud luncher

image

I got my get plugin testing builds ticked.
Instance id viewer works just fine but link in chat just fails to load when being installed

### PR DESCRIPTION
**Pull request by Diyagi**
Fixes #675 
This is kinda of an dirty fix.
Dalamud changed the way they process commands so they removed the regex's, i didnt had time to look closely on how they changed it so i just hardcoded their old regex's in the command processor.
Maybe would be an good idea to get rid of this custom one and stick with Dalamud one since would make maintenance easier...
and because i cant see why use an custom one.

### CODE REVIEW

**Comment by Diyagi** [comment]
Fixes #675

**Comment by SlashNephy** [comment]
Indeed, Divination has its own command system. This is because Divination used to be an ACT plugin, not a Dalamud plugin.
The command system in Divination is planned to be discontinued and will be replaced by that in Dalamud.

**Review by SlashNephy — APPROVED** [review]
Looks good for now.
I'll see this week whether I can replace Divination's command system with Dalamud's one.

**Comment by Diyagi** [comment]
> Indeed, Divination has its own command system. This is because Divination used to be an ACT plugin, not a Dalamud plugin, and to implement subcommands. The command system in Divination is planned to be discontinued and will be replaced by that in Dalamud.

Oh, i see, i did not knew it was an ACT plugin before, sorry, that makes a lot more sense now.

**Pull request merged**
