### PR TITLE
Update to API 11 and Lumina 5

### PR DESCRIPTION
**Pull request by Diyagi**
image
😿

### CODE REVIEW

**Comment by Diyagi** [comment]
For now only tested `AetheryteLinkInChat` and `FaloopIntegration`.
Surprisingly it was my first time dealing with non nullable so i would be happy if @SlashNephy have time for a quick feedback '-'
Other than that i will keep testing the two plugins i mentioned above for a bit more to see if theres any issues until dalamud releases.

I removed the Dalamud API overrides in the jsons bc the DalamudPackager should take care of that by itself, if you need that to build the plugin master list let me know and i will revert it.

**Comment by Diyagi** [comment]
Oh, and i almost forgot, ClickLib was archived, so we might need to find an fork of it.

**Comment by SlashNephy** [comment]
At the moment, in order to build correctly, it seems that CI must refer to https://github.com/goatcorp/dalamud-distrib/blob/main/api11/latest.zip.

**Comment by Diyagi** [comment]
> At the moment, in order to build correctly, it seems that CI must refer to https://github.com/goatcorp/dalamud-distrib/blob/main/api11/latest.zip.

Yes but we can wait until dalamud releases the update, also api11 has already gone into stg.

**Comment by Diyagi** [comment]
Dalamud is about to release 7.1 update, i tested the main plugins (`AetheryteLinkInChat` and `FaloopIntegration`) up til now and did not see any issues.

**Review by SlashNephy — APPROVED** [review]
OK, let's go!
I'll deal with the remaining plugins later.

**Pull request merged**
